from __future__ import annotations

import html
import io
import re
from pathlib import Path

from app.core.config import settings
from app.core.files import command_path, run_command
from app.core.formats import TEXT_DOCUMENTS, extension_of, valid_document_targets


def _glyph_currency_amounts(pdf_path: Path) -> set[str] | None:
    """Return the set of number strings that had a currency-glyph image
    immediately to their left somewhere in the PDF (see
    _restore_glyph_currency_symbols for why this detection exists), or None
    if no such glyphs were found. Used to patch amounts back into markdown
    generated by a separate structured converter (pymupdf4llm) without
    discarding that converter's table/heading reconstruction.
    """
    try:
        import pdfplumber
    except ImportError:
        return None

    amounts: set[str] = set()
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            glyph_images = [
                img for img in page.images
                if img["width"] < 12 and img["height"] < 12
                and abs(img["width"] - img["height"]) < 2
            ]
            if not glyph_images:
                continue
            words = page.extract_words(use_text_flow=False, keep_blank_chars=False)
            for glyph in glyph_images:
                row_mid = (glyph["top"] + glyph["bottom"]) / 2
                candidates = [
                    w for w in words
                    if w["x0"] >= glyph["x1"] - 1
                    and w["x0"] - glyph["x1"] < 15
                    and w["top"] <= row_mid <= w["bottom"]
                    and re.match(r"^[\d.,]+$", w["text"])
                ]
                if candidates:
                    nearest = min(candidates, key=lambda w: w["x0"])
                    amounts.add(nearest["text"])

    return amounts or None


def _restore_glyph_currency_symbols(pdf_path: Path) -> list[list[str]] | None:
    """Recover currency symbols that a PDF rendered as tiny raster images.

    Some report generators (this is common with institutional fee-receipt
    software) don't have a currency glyph in their embedded font subset, so
    they stamp a small image of the symbol next to the amount instead of
    drawing a text character. Every text extractor -- PyMuPDF, pdfminer,
    pdfplumber -- correctly reports no text there, because there genuinely
    isn't any; the symbol is a picture. Silently dropping it loses real
    information (whether an amount is a currency value at all), so this
    detects the specific, unambiguous pattern -- a small near-square image
    sitting immediately to the left of a number on the same text row -- and
    reinserts the symbol as a text character in front of that number.

    This only fires on that exact geometric pattern, never on bare numbers,
    so it can't misfire on page numbers, IDs, or dates that happen to be
    near an unrelated image.

    Returns a list of pages, each a list of line strings, or None if
    pdfplumber isn't available or the PDF has no such glyph images at all
    (the common case -- most PDFs render currency symbols as normal text).
    """
    try:
        import pdfplumber
    except ImportError:
        return None

    pages_out: list[list[str]] = []
    any_glyph_found = False

    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            glyph_images = [
                img for img in page.images
                if img["width"] < 12 and img["height"] < 12
                and abs(img["width"] - img["height"]) < 2
            ]
            words = page.extract_words(use_text_flow=False, keep_blank_chars=False)

            marked_word_ids: set[tuple[str, float, float]] = set()
            if glyph_images:
                for glyph in glyph_images:
                    row_mid = (glyph["top"] + glyph["bottom"]) / 2
                    candidates = [
                        w for w in words
                        if w["x0"] >= glyph["x1"] - 1
                        and w["x0"] - glyph["x1"] < 15
                        and w["top"] <= row_mid <= w["bottom"]
                        and re.match(r"^[\d.,]+$", w["text"])
                    ]
                    if candidates:
                        nearest = min(candidates, key=lambda w: w["x0"])
                        marked_word_ids.add((nearest["text"], round(nearest["top"], 1), round(nearest["x0"], 1)))
                        any_glyph_found = True

            lines_map: dict[float, list[dict]] = {}
            for w in words:
                lines_map.setdefault(round(w["top"], 1), []).append(w)

            page_lines: list[str] = []
            for top in sorted(lines_map.keys()):
                row_words = sorted(lines_map[top], key=lambda w: w["x0"])
                parts = []
                for w in row_words:
                    wid = (w["text"], round(w["top"], 1), round(w["x0"], 1))
                    parts.append(("\u20b9" + w["text"]) if wid in marked_word_ids else w["text"])
                page_lines.append(" ".join(parts))
            pages_out.append(page_lines)

    return pages_out if any_glyph_found else None


LIBREOFFICE_FILTER_MAP = {
    "pdf": "pdf",
    "docx": "docx",
    "doc": "doc:MS Word 97",
    "odt": "odt",
    "rtf": "rtf",
    "txt": "txt",
    "html": "html",
    "htm": "html",
    "xlsx": "xlsx",
    "xls": "xls:MS Excel 97",
    "ods": "ods",
    "csv": "csv",
    "pptx": "pptx",
    "ppt": "ppt:MS PowerPoint 97",
    "odp": "odp",
}


def _soffice() -> str:
    return command_path(
        settings.soffice_bin,
        [
            r"C:\Program Files\LibreOffice\program\soffice.exe",
            r"C:\Program Files (x86)\LibreOffice\program\soffice.exe",
        ],
    ) or ""


def _strip_markdown(value: str) -> str:
    value = re.sub(r"```.*?```", "", value, flags=re.S)
    value = re.sub(r"`([^`]*)`", r"\1", value)
    value = re.sub(r"!\[[^]]*\]\([^)]*\)", "", value)
    value = re.sub(r"\[([^]]+)\]\([^)]*\)", r"\1", value)
    value = re.sub(r"^#{1,6}\s*", "", value, flags=re.M)
    value = re.sub(r"[*_~]", "", value)
    return value


def _html_to_text(value: str) -> str:
    value = re.sub(r"<br\s*/?>", "\n", value, flags=re.I)
    value = re.sub(r"</(p|div|h[1-6]|li|tr)>", "\n", value, flags=re.I)
    value = re.sub(r"<[^>]+>", "", value)
    return html.unescape(value)


def _pdf_to_text(input_path: Path, output_path: Path) -> Path:
    restored = _restore_glyph_currency_symbols(input_path)
    if restored is not None:
        text = "\n\n".join("\n".join(page_lines) for page_lines in restored)
        output_path.write_text(text, encoding="utf-8")
        return output_path

    import fitz

    document = fitz.open(input_path)
    try:
        text = "\n\n".join(page.get_text("text") for page in document)
        output_path.write_text(text, encoding="utf-8")
    finally:
        document.close()
    return output_path


def _pdf_to_html(input_path: Path, output_path: Path) -> Path:
    import fitz

    document = fitz.open(input_path)
    try:
        sections = []
        for index, page in enumerate(document, start=1):
            page_text = html.escape(page.get_text("text"))
            page_text = page_text.replace("\n", "<br>\n")
            sections.append(
                f"<section><h2>Page {index}</h2><p>{page_text}</p></section>"
            )

        document_html = (
            "<!doctype html><html><head><meta charset='utf-8'>"
            "<title>Converted PDF</title></head><body>"
            + "".join(sections)
            + "</body></html>"
        )
        output_path.write_text(document_html, encoding="utf-8")
    finally:
        document.close()
    return output_path


def _pdf_block_text(block: dict) -> str:
    lines = []
    for line in block.get("lines", []):
        spans = [span.get("text", "") for span in line.get("spans", [])]
        text = "".join(spans).strip()
        if text:
            lines.append(text)
    return "\n".join(lines).strip()


def _block_font_size(block: dict) -> float:
    sizes: list[float] = []
    for line in block.get("lines", []):
        for span in line.get("spans", []):
            try:
                size = float(span.get("size", 11))
            except (TypeError, ValueError):
                size = 11
            if size > 0:
                sizes.append(size)
    return max(8.0, min(30.0, max(sizes, default=11.0)))


def _pdf_to_docx(input_path: Path, output_path: Path) -> Path:
    """Convert a PDF to an editable DOCX using pdf2docx.

    pdf2docx reconstructs real Word paragraphs, native tables (not text
    dumped into a single column), fonts, and image placement by analyzing
    the PDF's layout structure -- this is a purpose-built converter rather
    than a hand-rolled text-block dump, and it is what produces documents
    that actually look like the source PDF when opened in Word.
    """
    from pdf2docx import Converter

    converter = Converter(str(input_path))
    try:
        converter.convert(str(output_path))
    finally:
        converter.close()

    if not output_path.exists():
        raise RuntimeError("pdf2docx did not produce the requested output file.")
    return output_path


def _pdf_to_markdown(input_path: Path, output_path: Path) -> Path:
    """Convert a PDF to structured Markdown using PyMuPDF4LLM.

    Unlike a raw text dump, this detects headings (by font size), bold and
    italic runs, ordered/unordered lists, and tables, and emits them as
    proper GitHub-flavored Markdown in reading order.
    """
    import pymupdf4llm

    markdown_text = pymupdf4llm.to_markdown(str(input_path))

    amounts = _glyph_currency_amounts(input_path)
    if amounts:
        # Longest-first so "100000" is patched before a shorter number that
        # happens to be its substring gets a chance to match.
        for amount in sorted(amounts, key=len, reverse=True):
            markdown_text = re.sub(
                rf"(?<![\d.,\u20b9]){re.escape(amount)}(?![\d.,])",
                "\u20b9" + amount,
                markdown_text,
            )

    output_path.write_text(markdown_text, encoding="utf-8")
    return output_path


def _pdf_to_pptx(input_path: Path, output_path: Path) -> Path:
    """Create an editable PPTX approximation of a PDF.

    Each PDF page becomes a slide. Text becomes native PowerPoint text boxes
    and embedded raster images become native picture objects. Complex vector
    artwork may not map 1:1, which is inherent in PDF -> PowerPoint conversion.
    """
    import fitz
    from pptx import Presentation
    from pptx.enum.text import MSO_AUTO_SIZE
    from pptx.util import Inches, Pt

    pdf = fitz.open(input_path)
    prs = Presentation()

    # Remove the default starter slide so every PDF page maps exactly to one slide.
    while len(prs.slides):
        r_id = prs.slides._sldIdLst[0].rId
        prs.part.drop_rel(r_id)
        del prs.slides._sldIdLst[0]

    try:
        if len(pdf) == 0:
            raise ValueError("PDF contains no pages.")

        first_page = pdf[0]
        first_rect = first_page.rect
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(10 * first_rect.height / first_rect.width)

        for page in pdf:
            slide_width_pt = float(prs.slide_width) / 12700.0
            slide_height_pt = float(prs.slide_height) / 12700.0
            scale_x = slide_width_pt / page.rect.width if page.rect.width else 1.0
            scale_y = slide_height_pt / page.rect.height if page.rect.height else 1.0

            slide = prs.slides.add_slide(prs.slide_layouts[6])
            page_dict = page.get_text("dict")
            blocks = page_dict.get("blocks", [])
            blocks.sort(key=lambda block: (block.get("bbox", [0, 0, 0, 0])[1], block.get("bbox", [0, 0, 0, 0])[0]))

            for block in blocks:
                bbox = block.get("bbox") or [0, 0, 0, 0]
                x0, y0, x1, y1 = map(float, bbox)
                left = Inches(max(0.0, x0 * scale_x / 72.0))
                top = Inches(max(0.0, y0 * scale_y / 72.0))
                width = Inches(max(0.05, (x1 - x0) * scale_x / 72.0))
                height = Inches(max(0.05, (y1 - y0) * scale_y / 72.0))

                if block.get("type") == 1 and block.get("image"):
                    try:
                        slide.shapes.add_picture(
                            io.BytesIO(block["image"]),
                            left,
                            top,
                            width=width,
                            height=height,
                        )
                    except Exception:
                        continue
                    continue

                if block.get("type") != 0:
                    continue

                text = _pdf_block_text(block)
                if not text:
                    continue

                shape = slide.shapes.add_textbox(
                    left,
                    top,
                    width,
                    height,
                )

                frame = shape.text_frame
                frame.clear()
                frame.word_wrap = True
                frame.auto_size = MSO_AUTO_SIZE.NONE

                paragraph = frame.paragraphs[0]
                paragraph.text = text

                font = paragraph.runs[0].font
                font.name = "Arial"
                font.size = Pt(max(6, min(32, _block_font_size(block))))

            # If a page had no extractable objects, preserve its visual content
            # as a full-page raster image rather than returning an empty slide.
            if not slide.shapes:
                pix = page.get_pixmap(matrix=fitz.Matrix(1.5, 1.5), alpha=False)
                slide.shapes.add_picture(
                    io.BytesIO(pix.tobytes("png")),
                    0,
                    0,
                    width=prs.slide_width,
                    height=prs.slide_height,
                )

        prs.save(output_path)
    finally:
        pdf.close()

    return output_path


def convert_to_markdown_with_markitdown(input_path: Path, output_path: Path) -> Path:
    """Convert Word/PowerPoint/Excel/HTML/image files to Markdown using MarkItDown.

    MarkItDown (Microsoft, MIT-licensed) is a purpose-built converter for
    this exact job: it understands each container format natively (docx via
    python-docx/mammoth, xlsx via openpyxl, pptx via python-pptx, html via
    a real parser) rather than approximating structure from a text dump.
    """
    from markitdown import MarkItDown

    converter = MarkItDown(enable_plugins=False)
    result = converter.convert(str(input_path))
    output_path.write_text(result.text_content, encoding="utf-8")
    return output_path


def convert_with_libreoffice(input_path: Path, target_ext: str, out_dir: Path) -> Path:
    binary = _soffice()
    if not binary:
        raise RuntimeError(
            "LibreOffice is required for this conversion but was not found. "
            "Install LibreOffice, restart Kiwi, or set KIWI_SOFFICE_BIN."
        )

    filter_name = LIBREOFFICE_FILTER_MAP.get(target_ext, target_ext)
    args = [
        binary,
        "--headless",
        "--norestore",
        "--nolockcheck",
        "--nodefault",
        "--convert-to",
        filter_name,
        "--outdir",
        str(out_dir),
        str(input_path),
    ]

    try:
        run_command(args, timeout=240)
    except RuntimeError as exc:
        raise RuntimeError(
            f"LibreOffice could not convert '{input_path.name}' to .{target_ext}. {exc}"
        ) from exc

    produced = out_dir / f"{input_path.stem}.{target_ext}"
    if produced.exists():
        return produced

    matches = [
        path
        for path in out_dir.glob(f"{input_path.stem}.*")
        if path.is_file() and path.suffix.lower().lstrip(".") == target_ext
    ]
    if matches:
        return matches[0]

    raise RuntimeError(
        f"LibreOffice completed without producing the requested .{target_ext} output."
    )


def convert_document(input_path: Path, target_ext: str, out_dir: Path) -> Path:
    source_ext = extension_of(input_path.name)
    target_ext = target_ext.lower().lstrip(".")

    allowed = valid_document_targets(source_ext)
    if target_ext not in allowed:
        raise ValueError(f"Conversion from .{source_ext} to .{target_ext} is not supported.")

    out_dir.mkdir(parents=True, exist_ok=True)
    output_path = out_dir / f"{input_path.stem}.{target_ext}"

    if source_ext == "pdf":
        if target_ext == "txt":
            return _pdf_to_text(input_path, output_path)
        if target_ext == "html":
            return _pdf_to_html(input_path, output_path)
        if target_ext == "md":
            return _pdf_to_markdown(input_path, output_path)
        if target_ext == "docx":
            return _pdf_to_docx(input_path, output_path)
        if target_ext == "pptx":
            return _pdf_to_pptx(input_path, output_path)

    if source_ext in {"md", "markdown"} and target_ext == "txt":
        output_path.write_text(
            _strip_markdown(input_path.read_text(encoding="utf-8", errors="replace")),
            encoding="utf-8",
        )
        return output_path

    if source_ext in {"html", "htm"} and target_ext == "txt":
        output_path.write_text(
            _html_to_text(input_path.read_text(encoding="utf-8", errors="replace")),
            encoding="utf-8",
        )
        return output_path

    if source_ext == "txt" and target_ext == "md":
        output_path.write_text(
            input_path.read_text(encoding="utf-8", errors="replace"),
            encoding="utf-8",
        )
        return output_path

    if source_ext in {"html", "htm"} and target_ext == "md":
        output_path.write_text(
            _html_to_text(input_path.read_text(encoding="utf-8", errors="replace")),
            encoding="utf-8",
        )
        return output_path

    return convert_with_libreoffice(input_path, target_ext, out_dir)
