from __future__ import annotations

import html
import re
from pathlib import Path


def _glyph_currency_amounts(pdf_path: Path) -> set[str] | None:
    """Return the set of number strings that had a currency-glyph image
    immediately to their left somewhere in the PDF (see
    _restore_glyph_currency_symbols for why this detection exists), or None
    if no such glyphs were found. Used to patch amounts back into markdown
    generated by a separate structured converter (pymupdf4llm) without
    discarding that converter's table/heading reconstruction.
    """
    try:
        import pdfplumber
    except ImportError:
        return None

    amounts: set[str] = set()
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            glyph_images = [
                img for img in page.images
                if img["width"] < 12 and img["height"] < 12
                and abs(img["width"] - img["height"]) < 2
            ]
            if not glyph_images:
                continue
            words = page.extract_words(use_text_flow=False, keep_blank_chars=False)
            for glyph in glyph_images:
                row_mid = (glyph["top"] + glyph["bottom"]) / 2
                candidates = [
                    w for w in words
                    if w["x0"] >= glyph["x1"] - 1
                    and w["x0"] - glyph["x1"] < 15
                    and w["top"] <= row_mid <= w["bottom"]
                    and re.match(r"^[\d.,]+$", w["text"])
                ]
                if candidates:
                    nearest = min(candidates, key=lambda w: w["x0"])
                    amounts.add(nearest["text"])

    return amounts or None


def _restore_glyph_currency_symbols(pdf_path: Path) -> list[list[str]] | None:
    """Recover currency symbols that a PDF rendered as tiny raster images.

    Some report generators (this is common with institutional fee-receipt
    software) don't have a currency glyph in their embedded font subset, so
    they stamp a small image of the symbol next to the amount instead of
    drawing a text character. Every text extractor -- PyMuPDF, pdfminer,
    pdfplumber -- correctly reports no text there, because there genuinely
    isn't any; the symbol is a picture. Silently dropping it loses real
    information (whether an amount is a currency value at all), so this
    detects the specific, unambiguous pattern -- a small near-square image
    sitting immediately to the left of a number on the same text row -- and
    reinserts the symbol as a text character in front of that number.

    This only fires on that exact geometric pattern, never on bare numbers,
    so it can't misfire on page numbers, IDs, or dates that happen to be
    near an unrelated image.

    Returns a list of pages, each a list of line strings, or None if
    pdfplumber isn't available or the PDF has no such glyph images at all
    (the common case -- most PDFs render currency symbols as normal text).
    """
    try:
        import pdfplumber
    except ImportError:
        return None

    pages_out: list[list[str]] = []
    any_glyph_found = False

    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            glyph_images = [
                img for img in page.images
                if img["width"] < 12 and img["height"] < 12
                and abs(img["width"] - img["height"]) < 2
            ]
            words = page.extract_words(use_text_flow=False, keep_blank_chars=False)

            marked_word_ids: set[tuple[str, float, float]] = set()
            if glyph_images:
                for glyph in glyph_images:
                    row_mid = (glyph["top"] + glyph["bottom"]) / 2
                    candidates = [
                        w for w in words
                        if w["x0"] >= glyph["x1"] - 1
                        and w["x0"] - glyph["x1"] < 15
                        and w["top"] <= row_mid <= w["bottom"]
                        and re.match(r"^[\d.,]+$", w["text"])
                    ]
                    if candidates:
                        nearest = min(candidates, key=lambda w: w["x0"])
                        marked_word_ids.add((nearest["text"], round(nearest["top"], 1), round(nearest["x0"], 1)))
                        any_glyph_found = True

            lines_map: dict[float, list[dict]] = {}
            for w in words:
                lines_map.setdefault(round(w["top"], 1), []).append(w)

            page_lines: list[str] = []
            for top in sorted(lines_map.keys()):
                row_words = sorted(lines_map[top], key=lambda w: w["x0"])
                parts = []
                for w in row_words:
                    wid = (w["text"], round(w["top"], 1), round(w["x0"], 1))
                    parts.append(("\u20b9" + w["text"]) if wid in marked_word_ids else w["text"])
                page_lines.append(" ".join(parts))
            pages_out.append(page_lines)

    return pages_out if any_glyph_found else None


def _strip_markdown(value: str) -> str:
    value = re.sub(r"```.*?```", "", value, flags=re.S)
    value = re.sub(r"`([^`]*)`", r"\1", value)
    value = re.sub(r"!\[[^]]*\]\([^)]*\)", "", value)
    value = re.sub(r"\[([^]]+)\]\([^)]*\)", r"\1", value)
    value = re.sub(r"^#{1,6}\s*", "", value, flags=re.M)
    value = re.sub(r"[*_~]", "", value)
    return value


def _html_to_text(value: str) -> str:
    value = re.sub(r"<br\s*/?>", "\n", value, flags=re.I)
    value = re.sub(r"</(p|div|h[1-6]|li|tr)>", "\n", value, flags=re.I)
    value = re.sub(r"<[^>]+>", "", value)
    return html.unescape(value)


def _pdf_to_text(input_path: Path, output_path: Path) -> Path:
    restored = _restore_glyph_currency_symbols(input_path)
    if restored is not None:
        text = "\n\n".join("\n".join(page_lines) for page_lines in restored)
        output_path.write_text(text, encoding="utf-8")
        return output_path

    import fitz

    from app.services.pdf_analysis import analyze_pdf
    from app.services.pdf_ocr import ocr_available, ocr_page

    analysis = analyze_pdf(input_path)
    ocr_pages = set(analysis.ocr_page_indices) if (analysis.requires_ocr and ocr_available()) else set()

    document = fitz.open(input_path)
    try:
        parts = []
        for i, page in enumerate(document):
            if i in ocr_pages:
                try:
                    parts.append(ocr_page(page).text)
                    continue
                except Exception:
                    pass
            parts.append(page.get_text("text"))
        output_path.write_text("\n\n".join(parts), encoding="utf-8")
    finally:
        document.close()
    return output_path


def _pdf_to_html(input_path: Path, output_path: Path) -> Path:
    """Render a PDF to fixed-layout HTML.

    Delegates to app.services.pdf_render, which places every text span and
    image at its real page coordinates (absolute positioning per page)
    instead of flattening the document into a single scrolling text dump.
    Falls back to OCR per-page for scanned content. See pdf_render.py.
    """
    from app.services.pdf_render import pdf_to_html as _render_pdf_to_html

    return _render_pdf_to_html(input_path, output_path)


def _pdf_to_docx(input_path: Path, output_path: Path) -> Path:
    """Convert a PDF to an editable DOCX using pdf2docx.

    pdf2docx reconstructs real Word paragraphs, native tables (not text
    dumped into a single column), fonts, and image placement by analyzing
    the PDF's layout structure -- this is a purpose-built converter rather
    than a hand-rolled text-block dump, and it is what produces documents
    that actually look like the source PDF when opened in Word.

    Scanned pages have no text for pdf2docx to find (it reads the PDF's
    text layer, it doesn't run OCR itself), so before handing off, any page
    that `pdf_analysis` flags as needing OCR gets an invisible OCR text
    layer burned in first (fitz render_mode=3, "hidden text").

    pdf2docx has a dedicated `ocr` setting for exactly this: ocr=0 (default)
    ignores hidden text as noise, ocr=2 treats the *entire* document as
    OCR-sourced and extracts only the hidden text (dropping images). Since
    that's a single document-wide flag, a fully-scanned PDF can be converted
    in one ocr=2 pass, but a *mixed* PDF (some native pages, some scanned)
    can't -- one pass would either drop the scanned pages' text (ocr=0) or
    drop every native page's images (ocr=2). For that case this splits the
    PDF into single-document-mode runs per contiguous page group and merges
    the resulting docx files, so each page gets the extraction mode that
    actually matches its content.
    """
    from app.services.pdf_analysis import analyze_pdf
    from app.services.pdf_ocr import ocr_available

    from pdf2docx import Converter

    analysis = analyze_pdf(input_path)
    ocr_pages = set(analysis.ocr_page_indices) if (analysis.requires_ocr and ocr_available()) else set()

    if not ocr_pages:
        converter = Converter(str(input_path))
        try:
            converter.convert(str(output_path))
        finally:
            converter.close()
        if not output_path.exists():
            raise RuntimeError("pdf2docx did not produce the requested output file.")
        return output_path

    if len(ocr_pages) == analysis.page_count:
        # Whole document is scanned: one ocr=2 pass over the whole thing.
        ocr_path = output_path.with_suffix(".ocr_source.pdf")
        try:
            _burn_in_ocr_text_layer(input_path, ocr_path, sorted(ocr_pages))
            converter = Converter(str(ocr_path))
            try:
                converter.convert(str(output_path), ocr=2)
            finally:
                converter.close()
        finally:
            ocr_path.unlink(missing_ok=True)
        if not output_path.exists():
            raise RuntimeError("pdf2docx did not produce the requested output file.")
        return output_path

    # Mixed document: convert each contiguous run of same-mode pages
    # separately (native pages with ocr=0/default, scanned pages burned-in
    # with ocr=2), then splice the resulting single-page-range docx files
    # together in original page order.
    import fitz

    from docxcompose.composer import Composer
    from docx import Document as DocxDocument

    groups: list[tuple[bool, list[int]]] = []  # (is_ocr, [page_indices])
    for i in range(analysis.page_count):
        is_ocr = i in ocr_pages
        if groups and groups[-1][0] == is_ocr:
            groups[-1][1].append(i)
        else:
            groups.append((is_ocr, [i]))

    part_paths: list[Path] = []
    src_doc = fitz.open(input_path)
    try:
        for gi, (is_ocr, indices) in enumerate(groups):
            part_pdf = output_path.with_suffix(f".part{gi}.pdf")
            part_docx = output_path.with_suffix(f".part{gi}.docx")
            sub = fitz.open()
            try:
                sub.insert_pdf(src_doc, from_page=indices[0], to_page=indices[-1])
                if is_ocr:
                    _burn_in_ocr_text_layer_inplace(sub, list(range(len(indices))))
                sub.save(part_pdf)
            finally:
                sub.close()

            converter = Converter(str(part_pdf))
            try:
                if is_ocr:
                    converter.convert(str(part_docx), ocr=2)
                else:
                    converter.convert(str(part_docx))
            finally:
                converter.close()
            part_paths.append(part_docx)
            part_pdf.unlink(missing_ok=True)
    finally:
        src_doc.close()

    try:
        master = DocxDocument(str(part_paths[0]))
        composer = Composer(master)
        for extra in part_paths[1:]:
            composer.append(DocxDocument(str(extra)))
        composer.save(str(output_path))
    finally:
        for p in part_paths:
            p.unlink(missing_ok=True)

    if not output_path.exists():
        raise RuntimeError("pdf2docx did not produce the requested output file.")
    return output_path


def _burn_in_ocr_text_layer_inplace(doc, page_indices: list[int]) -> None:
    """Same as `_burn_in_ocr_text_layer` but mutates an already-open fitz
    Document in place rather than reading/writing a file, for use when the
    document is a short-lived in-memory page-range extract.
    """
    from app.services.pdf_ocr import ocr_lines

    for idx in page_indices:
        if idx >= len(doc):
            continue
        page = doc[idx]
        try:
            lines = ocr_lines(page)
        except Exception:
            continue
        for line in lines:
            for word in line:
                if not word.text.strip():
                    continue
                height = max(1.0, word.y1 - word.y0)
                try:
                    page.insert_text(
                        (word.x0, word.y1 - height * 0.15),
                        word.text,
                        fontsize=height * 0.9,
                        render_mode=3,
                    )
                except Exception:
                    continue


def _burn_in_ocr_text_layer(input_path: Path, output_path: Path, page_indices: list[int]) -> Path:
    """Write a copy of the PDF where the given pages have an invisible OCR
    text layer added over the existing page content, using PyMuPDF's
    invisible-text render mode. Downstream tools that read the PDF's text
    layer (pdf2docx, pymupdf4llm, pdfplumber) then see real, positioned text
    on pages that previously had none, without altering how the page looks
    when viewed or printed.
    """
    import fitz

    from app.services.pdf_ocr import ocr_lines

    doc = fitz.open(input_path)
    try:
        for idx in page_indices:
            if idx >= len(doc):
                continue
            page = doc[idx]
            try:
                lines = ocr_lines(page)
            except Exception:
                continue
            for line in lines:
                for word in line:
                    if not word.text.strip():
                        continue
                    height = max(1.0, word.y1 - word.y0)
                    try:
                        page.insert_text(
                            (word.x0, word.y1 - height * 0.15),
                            word.text,
                            fontsize=height * 0.9,
                            render_mode=3,  # invisible -- text is selectable/extractable but not painted
                        )
                    except Exception:
                        continue
        doc.save(output_path)
    finally:
        doc.close()
    return output_path


def _pdf_to_markdown(input_path: Path, output_path: Path) -> Path:
    """Convert a PDF to structured Markdown using PyMuPDF4LLM.

    Unlike a raw text dump, this detects headings (by font size), bold and
    italic runs, ordered/unordered lists, and tables, and emits them as
    proper GitHub-flavored Markdown in reading order.

    Scanned pages have no text for pymupdf4llm to structure, so pages that
    `pdf_analysis` flags as needing OCR get an invisible OCR text layer
    burned in first (see `_burn_in_ocr_text_layer`), the same way as for
    PDF -> DOCX. pymupdf4llm then has real text to work with on those pages
    too, instead of emitting a blank section.
    """
    import pymupdf4llm

    from app.services.pdf_analysis import analyze_pdf
    from app.services.pdf_ocr import ocr_available

    source_for_conversion = input_path
    analysis = analyze_pdf(input_path)
    if analysis.requires_ocr and ocr_available():
        ocr_path = output_path.with_suffix(".ocr_source.pdf")
        try:
            source_for_conversion = _burn_in_ocr_text_layer(input_path, ocr_path, analysis.ocr_page_indices)
        except Exception:
            source_for_conversion = input_path

    try:
        markdown_text = pymupdf4llm.to_markdown(str(source_for_conversion))
    finally:
        if source_for_conversion != input_path:
            source_for_conversion.unlink(missing_ok=True)

    amounts = _glyph_currency_amounts(input_path)
    if amounts:
        # Longest-first so "100000" is patched before a shorter number that
        # happens to be its substring gets a chance to match.
        for amount in sorted(amounts, key=len, reverse=True):
            markdown_text = re.sub(
                rf"(?<![\d.,\u20b9]){re.escape(amount)}(?![\d.,])",
                "\u20b9" + amount,
                markdown_text,
            )

    output_path.write_text(markdown_text, encoding="utf-8")
    return output_path


def _pdf_to_pptx(input_path: Path, output_path: Path) -> Path:
    """Create an editable PPTX approximation of a PDF.

    Delegates to app.services.pdf_render, which resolves real font
    family/weight/style per run (instead of forcing Arial), OCRs pages that
    have no native text layer, and falls back to a high-resolution
    full-page image only for pages dominated by vector art that can't be
    reconstructed as editable shapes. See pdf_render.py.
    """
    from app.services.pdf_render import pdf_to_pptx as _render_pdf_to_pptx

    return _render_pdf_to_pptx(input_path, output_path)


def convert_to_markdown_with_markitdown(input_path: Path, output_path: Path) -> Path:
    """Convert Word/PowerPoint/Excel/HTML/image files to Markdown using MarkItDown.

    MarkItDown (Microsoft, MIT-licensed) is a purpose-built converter for
    this exact job: it understands each container format natively (docx via
    python-docx/mammoth, xlsx via openpyxl, pptx via python-pptx, html via
    a real parser) rather than approximating structure from a text dump.
    """
    from markitdown import MarkItDown

    converter = MarkItDown(enable_plugins=False)
    result = converter.convert(str(input_path))
    output_path.write_text(result.text_content, encoding="utf-8")
    return output_path

